### ISSUE TITLE
Setup a 2nd prod environment

### ISSUE THREAD

**Issue by bowd** [celo-org/komenci#133]
### Overview

We want to setup a 2nd prod environment in SE Asia and add that to the front door

**Comment by bowd** [comment]
@codyborn, spoke to @eruizgar91 about this and he said that he would need you to setup the resources in Azure first and then he can take it from there. Let us know if that's ok or you want to approach things differently.

**Comment by codyborn** [comment]
@bowd that works for me. I'll setup the infra and fund the new relayers today.
