### ISSUE TITLE
Improve correlation of errors in logs

### ISSUE THREAD

**Issue by codyborn** [celo-org/komenci#150]
Example of Komenci errors:
https://console.cloud.google.com/logs/viewer?expandAll=false&timestamp=2020-12-17T20:30:16.134000000Z&dateRangeStart=2020-12-17T18:20:17.371Z&dateRangeEnd=2020-12-17T18:30:17.371Z&project=celo-testnet-production&minLogLevel=0&customFacets=&limitCustomFacetWidth=true&advancedFilter=logName:%22komenci.app.rc1%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22rc1%22%0Aresource.labels.container_name%3D%22komenci-onboarding%22%0A&interval=CUSTOM&scrollTimestamp=2020-12-17T18:30:07.165007248Z

We have no way to correlate the error to a session Id or account address. We need these to find matching logs in Valora to get a full picture of what's going on. This work is to add these items to the error logs:
- SessionId
- EOA
- MTW
- Anything else that can help us correlate

**Comment by bowd** [comment]
This was handled :+1:
